service: sms-sender
provider:
  name: aws
  region: us-east-1

functions:  
  # registerreceiver:
  #   handler: registerReceiver.lambda_handler
  #   runtime: python3.7
  #   events:
  #     - sns: sns-topic
  #     - http:
  #         path: register-receiver
  #         method: post
  #         cors: true

  sendSMS:
    handler: sendSMS.lambda_handler
    runtime: python3.7
    events:
      - http:
          path: sms
          method: post
          cors: true
