image: node:latest

stages:
  - deploy

production:
  stage: deploy
  only:
    - master
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - ./build.sh
  environment: production

