service: yb-hackathon-profile

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: profile/create.create
    events:
      - http:
          path: profile
          method: post
          cors: true

  list:
    handler: profile/list.list
    events:
      - http:
          path: profile
          method: get
          cors: true

  get:
    handler: profile/get.get
    events:
      - http:
          path: profile/{id}
          method: get
          cors: true

  update:
    handler: profile/update.update
    events:
      - http:
          path: profile/{id}
          method: put
          cors: true

  delete:
    handler: profile/delete.delete
    events:
      - http:
          path: profile/{id}
          method: delete
          cors: true

resources:
  Resources:
    ProfileDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
