service: yb-hackathon-stream
provider:
  name: aws
  region: eu-central-1

resources: 
  Resources:
    IdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties: 
        IdentityPoolName: stream-identity-pool
        AllowUnauthenticatedIdentities: true

    CognitoUnAuthorizedRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal: 
                Federated: "cognito-identity.amazonaws.com"
              Action: 
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals: 
                  "cognito-identity.amazonaws.com:aud": 
                    Ref: IdentityPool 
                  "ForAnyValue:StringLike":
                    "cognito-identity.amazonaws.com:amr": unauthenticated
        Policies:
          - PolicyName: "CognitoUnauthorizedPolicy"
            PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
                - Effect: "Allow"
                  Action:
                    - "kinesis:*"
                    - "cognito-sync:*"
                  Resource: "*"        