service: text-sentiment-analysis
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "comprehend:*"
        - "s3:ListAllMyBuckets"
        - "s3:ListBucket"
        - "s3:GetBucketLocation"
        - "iam:ListRoles"
        - "iam:GetRole"
        - "kinesis:*"
      Resource: "*"

functions:
  imageAnalysis:
    handler: sentiment.handler
    events:
      - http:
          path: sentiment
          method: post
  sentinel:
    handler: sentinel.handler

resources:
  Resources:
    KinesisFirehose:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamName: "yb-firehose"
        DeliveryStreamType: "KinesisStreamAsSource"
        KinesisStreamSourceConfiguration:
          - KinesisStreamARN: "arn:aws:kinesis:eu-central-1:829534015160:stream/Foo"
            RoleARN: "arn:aws:iam::829534015160:role/RoleForKinesisComprehend"
        S3DestinationConfiguration:
          - BucketARN: "arn:aws:s3:::yb-hackathon"
            BufferingHints:
              - IntervalInSeconds: "60"
                SizeInMBs: "100"
            CompressionFormat: "GZIP"
            RoleARN: "arn:aws:iam::829534015160:role/RoleForKinesisComprehend"
